const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw . Jelly bear claw  bears lollipop cotton candy  bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie  Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet.  croissant macaroon dessert. Chocolate cake  pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy  8-bit ,  viral butcher  mi   woke bicycle rights brunch before they sold out ramps. Twee shabby chic  flannel, enamel pin vape four . Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical  mi narwhal echo park .`,
  `Zombie ipsum  ab viral inferno, nam rick grimes . De carne lumbering  corpora .  brains sit​​, vel  De a gorger  undead survivor dictum . Hi mindless  soulless , imo evil stalking    cerebella . Qui animated corpse, cricket bat max  . The voodoo  flesh eater,   virus.  tattered for  oculi  go lum  brains an Undead zombies.putrid voodoo horror. Nigh .`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! , your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
  I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella.  melted cheese port- cheese and wine melted cheese . Everyone loves blue  everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian  who moved my cheese  port gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth.  raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray  cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe  kitsch tumeric cloud bread vaporware pork belly  mi.`,
  `Man braid celiac synth , pitchfork fam salvia waistcoat bitters gentrify four . Pitchfork semiotics post-ironic vegan. Tofu meditation  hashtag semiotics .  vape tilde. Prism  farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts selvage trust fund vape.`,
  `Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
];
export default text;
